#!/usr/bin/python
# Copyright (c) 2011 Technische Universitaet Muenchen, Informatik Lehrstuhl IX.
# Author: Federico Ruiz-Ugalde
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# This program simulates the sliding movement of a box on top of a plane. It is meant to be used together with roboviewer and xfinger_feeder or slider_control_simple


import sys
sys.path.append("../../control/motionControl")
sys.path.append("../../tools/python/computer_graphics")
from pyrovito.pyrovito_utils import Roboviewer_objects
from arcospyu.kdl_helpers import rot_vector_angle, my_adddelta, my_diff
from arcospyu.control.control_loop import Controlloop
from numpy import array,identity, concatenate,dot ,sqrt, cross, arctan, pi
from numpy.linalg import norm,inv
from numpy.random import normal
from PyKDL import Frame,addDelta, Twist, diff
from arcospyu.computer_graphics.pluecker_test import polygon_pluecker_test, triangle_ray_intersection, plane_ray_intersection
import time
from cmoc.objects.sliding import LS
from arcospyu.yarp_tools.yarp_comm_helpers import new_port, readListPort, write_narray_port


class Loop(Controlloop):

    def visualize(self,points=[],vectors=[]):
        for local,ref_frame,vis_id in points:
            if len(local)==3:
                #for points
                pose=dot(ref_frame,homo_matrix(trans=local))
            else:
                #for frames
                pose=dot(ref_frame,local)
            self.view_objects.send_prop(vis_id,"pose",
                                        pose.reshape(16).tolist())

        for vector_local,ref_frame_vector,point_local,ref_frame_point,vis_id in vectors:
            point=dot(ref_frame_point,homo_matrix(trans=point_local))
            self.view_objects.send_prop(vis_id,"pose",
                                        point.reshape(16).tolist())
            vector=dot(ref_frame_vector[:3,:3],vector_local)
            self.view_objects.send_prop(vis_id,"axis",0.5*vector/norm(vector))

    def set_params(self,params):
        vars(self).update(params) #takes the dictionary params and puts everything in variables of the class
        base_name="/slider_sim"
        self.xfinger_in_port=new_port(base_name+"/xfinger:in","in", "/xfinger_feeder/xfinger:out",timeout=1.)
        self.xo_out_port=new_port(base_name+"/xo:out","out", "/planar_control/xo:in", timeout=1.)
        self.fc_out_port=new_port(base_name+"/ffinger:out","out", "/ffinger_out", timeout=1.)
        #do a parameter input port (for simulation only)
        #variables
        #robot-object contact
        #self.Vc=array([0.1,0.,0.])
        #self.contact_pos_local=array([-0.5,-0.2,0.])
        #self.contact_pose=identity(4)
        #self.contact_pose[:3,3]=array([-0.5,-0.2,0.])
        #self.contact_vel_twist=array([0.,0.0,0.,0.,0.,0.])
        #self.contact_vel_twist[:3]=self.Vc

        self.finger_vel_twist=array([0.,0.,0.,0.,0.,0.])
        self.finger_data_good=False
        self.finger_data_good_counter=0
        self.finger_data_good_max_counter=10
        self.finger_pose=identity(4)
        #self.finger_pose[:3,3]=array(readListPort(self.xfinger_in_port,blocking=True))
        self.last_time=time.time()

        #self.Vc=array([0.1,0.,0.])
        #self.contact_pose[:3,3]=array([-1,-0.5,0.])

        #box
        self.box_dim=[.5,0.5,0.3]
        self.box_center=array([0.,0.,0])
        self.box_planes=[[(1.,0.,0),(self.box_dim[0]/2.,0.,0.)], #(normal, point)
                        [(-1.,0.,0),(-self.box_dim[0]/2.,0.,0.)],
                        [(0.,1.,0),(0.,self.box_dim[1]/2.,0.)],
                        [(0.,-1.,0),(0,-self.box_dim[1]/2.,0.)],
                        [(0.,0.,1),(0.,0.,self.box_dim[2]/2.)],
                        [(0.,0.,-1),(0.,0.,-self.box_dim[2]/2.)]]
        self.box_vertices={
            0: array([[self.box_dim[0]/2,-self.box_dim[1]/2,-self.box_dim[2]/2],
                      [self.box_dim[0]/2,self.box_dim[1]/2,-self.box_dim[2]/2],
                      [self.box_dim[0]/2,self.box_dim[1]/2,self.box_dim[2]/2],
                      [self.box_dim[0]/2,-self.box_dim[1]/2,self.box_dim[2]/2]]),
            1: array([[-self.box_dim[0]/2,-self.box_dim[1]/2,-self.box_dim[2]/2],
                      [-self.box_dim[0]/2,-self.box_dim[1]/2,self.box_dim[2]/2],
                      [-self.box_dim[0]/2,self.box_dim[1]/2,self.box_dim[2]/2],
                      [-self.box_dim[0]/2,self.box_dim[1]/2,-self.box_dim[2]/2]]),
            2: array([[-self.box_dim[0]/2,self.box_dim[1]/2,-self.box_dim[2]/2],
                      [-self.box_dim[0]/2,self.box_dim[1]/2,self.box_dim[2]/2],
                      [self.box_dim[0]/2,self.box_dim[1]/2,self.box_dim[2]/2],
                      [self.box_dim[0]/2,self.box_dim[1]/2,-self.box_dim[2]/2]]),
            3: array([[self.box_dim[0]/2,-self.box_dim[1]/2,-self.box_dim[2]/2],
                      [self.box_dim[0]/2,-self.box_dim[1]/2,self.box_dim[2]/2],
                      [-self.box_dim[0]/2,-self.box_dim[1]/2,self.box_dim[2]/2],
                      [-self.box_dim[0]/2,-self.box_dim[1]/2,-self.box_dim[2]/2]]),
            4: array([[-self.box_dim[0]/2,-self.box_dim[1]/2,self.box_dim[2]/2],
                      [self.box_dim[0]/2,-self.box_dim[1]/2,self.box_dim[2]/2],
                      [self.box_dim[0]/2,self.box_dim[1]/2,self.box_dim[2]/2],
                      [-self.box_dim[0]/2,self.box_dim[1]/2,self.box_dim[2]/2]]),
            5: array([[-self.box_dim[0]/2,self.box_dim[1]/2,-self.box_dim[2]/2],
                      [self.box_dim[0]/2,self.box_dim[1]/2,-self.box_dim[2]/2],
                      [self.box_dim[0]/2,-self.box_dim[1]/2,-self.box_dim[2]/2],
                      [-self.box_dim[0]/2,-self.box_dim[1]/2,-self.box_dim[2]/2]])}

        self.finger_object_face=1
        self.table_object_face=5
        self.view_objects.send_prop(self.box_id,"scale",self.box_dim)
        box_id_offset=identity(4)
        box_id_offset[:3,3]=array([0.,0.,0.])
        self.view_objects.send_prop(self.box_id,"pose_offset",
                                    box_id_offset.reshape(16).tolist())
        self.weight_force=2.
        self.friction_finger_z_force=0.
        self.friction_coef_object_table=1.
        self.friction_coef_finger_object=0.4
        self.fmax=self.friction_coef_object_table*(self.weight_force-self.friction_finger_z_force)
        self.mmax_base=LS.calc_mmax_analytic(self.friction_coef_object_table,1.,self.box_dim[0],self.box_dim[1])
        self.mmax=self.mmax_base*(self.weight_force-self.friction_finger_z_force)
        print "fmax, mmax", self.fmax, self.mmax

        #objects
        self.box_pose=identity(4)
        self.box_pose[:3,3]=array([1.85,0.2,0.])
        self.box_vel_twist=array([0.0,0.0,0.,0.,0.,0.])
        self.box_pose_out=array(self.box_pose)

        self.test_pose=identity(4)
        self.test_pose[1,3]=-1.
        self.test_vel_twist=array([0.,0.0,0.,0.,0.,0.])
        self.test_vel_twist[:3]=self.finger_vel_twist[:3]

    def process(self):
        vis_vectors=[]
        vis_points=[]
        print

        #reading finger pose and calculating new speed
        self.new_finger_pose=identity(4)
        #print "here"
        result=readListPort(self.xfinger_in_port,blocking=False)
        self.cur_time=time.time()
        dt=self.cur_time-self.last_time
        self.last_time=self.cur_time
        self.finger_data_good_counter+=1
        if self.finger_data_good_counter>self.finger_data_good_max_counter:
            self.finger_data_good=False
        if result:
            self.new_finger_pose[:3,3]=array(result)
            if self.finger_data_good:
                self.finger_vel_twist[:3]=my_diff(self.finger_pose,
                                                  self.new_finger_pose, dt)[:3]
                self.finger_pose=self.new_finger_pose
            else:
                self.finger_pose[:3,3]=array(result)
            self.finger_data_good_counter=0
            self.finger_data_good=True
        print "finger vel", self.finger_vel_twist

        # finger local calculation
        self.finger_vel_local=dot(inv(self.box_pose[:3,:3]),self.finger_vel_twist[:3])
        self.finger_pos_local=dot(inv(self.box_pose),self.finger_pose)[:3,3]
#        print "Finger pos local", self.finger_pos_local


        #first we find if finger is touching box
        touch,self.finger_object_face=find_finger_object_face(self.finger_vel_local,self.finger_pos_local,
                                      self.box_vertices, self.box_planes)

        #for finger vel z
        print "vel local", self.finger_vel_local
        if self.finger_vel_local[2]!=0.:
            friction_coef_finger_object_xy=self.friction_coef_finger_object*\
                                        abs(self.finger_vel_local[1])/\
                                        norm(array([self.finger_vel_local[1],
                                                    self.finger_vel_local[2]]))
            # friction_coef_finger_object_xy= abs(self.finger_vel_local[1])/\
            # norm(array([self.finger_vel_local[1],
            # self.finger_vel_local[2]]))
        else:
            friction_coef_finger_object_xy=self.friction_coef_finger_object
        friction_coef_finger_object_xy=self.friction_coef_finger_object # TODO 

        fmax2=self.friction_coef_object_table*\
                   (self.weight_force-self.friction_finger_z_force)
        mmax2=self.mmax_base*(self.weight_force-self.friction_finger_z_force)
        print "fmax2, mmax2", fmax2,mmax2, friction_coef_finger_object_xy
        #LC_c_matrix=nc_to_forces_map(fmax2,mmax2,self.finger_pos_local)
        #nc_max,nc_min,fc_max,fc_min=nc_max_min(
        #    array(self.box_planes[self.table_object_face][0]),
        #    array(self.box_planes[
        #    self.finger_object_face][0]),
        #   friction_coef_finger_object_xy,
        #   inv(LC_c_matrix))

        #end finger vel z

        if touch:
            #velocity of box in point of contact (when finger slides or not)
            vc_local,result=vc_from_vfinger(self.finger_vel_local,
                                            self.finger_pos_local,
                                       self.box_vertices,self.box_planes,
                                array(self.box_planes[self.finger_object_face][0]),
                                array(self.box_planes[self.table_object_face][0]),
                                friction_coef_finger_object_xy,fmax2,
                                       mmax2)
            # print "Vc local", vc_local

            #finger touching and pushing object
            #table-object friction model
            Vo_local,fc_local,fo_local=vc_to_vo_linear_model(
                vc_local, self.finger_pos_local, fmax2, mmax2)
            cor_local=array([-Vo_local[1],Vo_local[0],0.])/Vo_local[2]
            Vo_local=array([Vo_local[0],Vo_local[1],0.,0.,0.,Vo_local[2]])
            # self.friction_finger_z_force=fc_local[1]*self.finger_vel_local[2]/\
            # self.finger_vel_local[1]
            if self.finger_vel_local[2]!=0.:
                self.friction_finger_z_force=self.friction_coef_finger_object*fc_local[0]*self.finger_vel_local[2]/norm(array([self.finger_vel_local[1],self.finger_vel_local[2]]))
            else:
                self.friction_finger_z_force=0.
            print "fc local, vc local", fc_local, vc_local/norm(vc_local)
            print "force z", self.friction_finger_z_force
        else:
            vc_local=array([0.]*3)
            #finger not touching, no movement
            Vo_local=array([0.]*6)
            fo_local=array([0.]*3)
            fc_local=array([0.]*3)
            cor_local=array([0.]*3)
        # box twist
        self.box_vel_twist[:3]=dot(self.box_pose[:3,:3],
                                   Vo_local[:3])
        self.box_vel_twist[3:]=Vo_local[3:]
        #fc_local to fc
        self.fc=dot(self.box_pose[:3,:3],fc_local)

        #send through yarp
        write_narray_port(self.fc_out_port,self.fc)
        write_narray_port(self.xo_out_port,self.box_pose_out.reshape(16))

        #box visualization
        box_top_pose=array(self.box_pose)
        #box_top_pose[2,3]=+0.2
        vis_points+=[(self.box_pose_out,identity(4),self.box_id), 
                    #(self.contact_pos_local,box_top_pose,self.contact_id),
                    (self.finger_pose,identity(4),self.contact_id),
                    (cor_local,box_top_pose,self.cor_id)]
        foxy_local=array(fo_local)
        foxy_local[2]=0.
        voxy_local=array(Vo_local)[:3]
        voxy_local[2]=0.
        vis_vectors+=[(self.finger_vel_twist[:3],identity(4),
                      self.finger_pose[:3,3], identity(4),
                      self.vc_id),
                      #(fc_local,self.box_pose,
                      #self.finger_pos_local, box_top_pose,
                      #self.fc_id),
                      (self.fc,identity(4),
                      self.finger_pose[:3,3], identity(4),
                      self.fc_id),
                      #(foxy_local,self.box_pose,
                      #array([0.,0.,0.]), box_top_pose,
                      #self.fo_id),
                      #(voxy_local,self.box_pose,
                      #array([0.,0.,0.]), box_top_pose,
                      #self.vo_id)
                      ]
                      

        #test visualization
#        vis_points+=[(self.test_pose,identity(4),self.test_id)]

        #visualization update
        self.visualize(points=vis_points, vectors=vis_vectors)


        #position update
        self.box_pose=my_adddelta(self.box_pose,self.box_vel_twist,dt)

        #gaussian noise to output information.
        self.box_pose_out=array(self.box_pose)
        noise_level=0.1*0.3*array([0.02,0.02,5.0*pi/180.0])
        self.box_pose_out[:2,3]=normal(loc=self.box_pose_out[:2,3], scale=noise_level[:2], size=(2))
        random_z_angle=normal(loc=0.,scale=noise_level[2])
        table_object_normal=-array(self.box_planes[self.table_object_face][0])
        print "table normal", table_object_normal
        random_rot_frame=identity(4)
        random_rot_frame[:2,3]=0*array([0.0,0.01]) #camera offset error
        random_rot_frame[:3,:3]=rot_vector_angle(table_object_normal, random_z_angle)
        self.box_pose_out=dot(self.box_pose_out, random_rot_frame)
        #self.test_pose=my_adddelta(self.test_pose,self.test_vel_twist,self.period)
        #self.contact_pose=my_adddelta(self.contact_pose,self.contact_vel_twist,
        #                              self.period)
        #self.finger_pose=my_adddelta(self.finger_pose,self.finger_vel_twist,
                                      #self.period)

def main():
    view_objects=Roboviewer_objects("/planar_slider","/lwr/roboviewer", 2000)
    box_id=view_objects.create_object("box")
    view_objects.send_prop(box_id,"scale",[1.,1.,0.1])
    view_objects.send_prop(box_id,"timeout",[-1])
    view_objects.send_prop(box_id,"color",[0.5,0.5,0.5])

    contact_id=view_objects.create_object("sphere")
    view_objects.send_prop(contact_id,"scale",[0.05,0.05,0.05])
    view_objects.send_prop(contact_id,"timeout",[-1])

    cor_id=view_objects.create_object("sphere")
    view_objects.send_prop(cor_id,"scale",[0.05,0.05,0.05])
    view_objects.send_prop(cor_id,"timeout",[-1])
    view_objects.send_prop(cor_id,"color",[1,0,0])

    vc_id=view_objects.create_object("arrow")
    view_objects.send_prop(vc_id,"scale",[0.5,0.5,0.125])
    vc_id_offset=identity(4)
    vc_id_offset[:3,3]=array([0.,0.,-1.])
    view_objects.send_prop(vc_id,"pose_offset",vc_id_offset.reshape(16).tolist())
    view_objects.send_prop(vc_id,"timeout",[-1])
    view_objects.send_prop(vc_id,"color",[1,0,0])

    fc_id=view_objects.create_object("arrow")
    view_objects.send_prop(fc_id,"scale",[0.5,0.5,0.125])
    fc_id_offset=identity(4)
    fc_id_offset[:3,3]=array([0.,0.,-1.])
    view_objects.send_prop(fc_id,"pose_offset",fc_id_offset.reshape(16).tolist())
    view_objects.send_prop(fc_id,"timeout",[-1])
    view_objects.send_prop(fc_id,"color",[0,1,0])

    vo_id=view_objects.create_object("arrow")
    view_objects.send_prop(vo_id,"scale",[0.5,0.5,0.125])
    vo_id_offset=identity(4)
    vo_id_offset[:3,3]=array([0.,0.,-1.])
    view_objects.send_prop(vo_id,"pose_offset",vo_id_offset.reshape(16).tolist())
    view_objects.send_prop(vo_id,"timeout",[-1])
    view_objects.send_prop(vo_id,"color",[1,0,0])

    fo_id=view_objects.create_object("arrow")
    view_objects.send_prop(fo_id,"scale",[0.5,0.5,0.125])
    fo_id_offset=identity(4)
    fo_id_offset[:3,3]=array([0.,0.,-1.])
    view_objects.send_prop(fo_id,"pose_offset",fo_id_offset.reshape(16).tolist())
    view_objects.send_prop(fo_id,"timeout",[-1])
    view_objects.send_prop(fo_id,"color",[0,1,0])

#    test_id=view_objects.create_object("sphere")
#    view_objects.send_prop(test_id,"scale",[0.1,0.1,0.1])
#    view_objects.send_prop(test_id,"timeout",[-1])
#    view_objects.send_prop(test_id,"color",[1,0,0])


    control_loop=Loop(15)
    control_loop.loop(view_objects=view_objects,box_id=box_id,contact_id=contact_id,vc_id=vc_id,fc_id=fc_id,cor_id=cor_id,fo_id=fo_id,vo_id=vo_id)
    

    raw_input()


if __name__=="__main__":
    main()
